spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:filmorate_test_db;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
  main:
    banner-mode: off

logging:
  level:
    org.zalando.logbook: WARN
    org.springframework.web: WARN
    ru.yandex.practicum.filmorate: WARN
    org.springframework.jdbc: WARN
    org.springframework.boot: WARN
    org.springframework: WARN