spring:
  threads:
    virtual:
      enabled: true
  profiles:
    active: db
  config:
    import: "optional:application-db.yml,optional:application-in-memory.yml" # Импортируем конфигурации профилей

logging:
  level:
    org.zalando.logbook: TRACE
    org.springframework.web: DEBUG
    ru.yandex.practicum.filmorate: DEBUG
    org.springframework.jdbc: DEBUG

server:
  port: 8088

validation:
  film:
    description:
      max-length: 200
    release-date:
      earliest: "1895-12-28"