spring:
  threads:
    virtual:
      enabled: true

logging:
  level:
    org.zalando.logbook: TRACE

logbook:
  format:
    style: json

server:
  port: 8080
validation:
  film:
    description:
      max-length: 200
    release-date:
      earliest: "1895-12-28"
